export enum JournalEntryType {
  OWNER_CONTRIBUTION = 'OWNER_CONTRIBUTION',
  OWNER_WITHDRAWAL = 'OWNER_WITHDRAWAL',
  CASH_BANK_TRANSFER = 'CASH_BANK_TRANSFER',
  EXPENSE_PAYMENT = 'EXPENSE_PAYMENT',
  SALE_RECEIPT = 'SALE_RECEIPT',
  PURCHASE = 'PURCHASE',
  SUPPLIER_PAYMENT = 'SUPPLIER_PAYMENT',
  OPENING_BALANCE = 'OPENING_BALANCE',
}
