export enum JournalEntryType {
  OWNER_CONTRIBUTION = 'OWNER_CONTRIBUTION',
  OWNER_WITHDRAWAL = 'OWNER_WITHDRAWAL',
  CASH_BANK_TRANSFER = 'CASH_BANK_TRANSFER',
  EXPENSE_PAYMENT = 'EXPENSE_PAYMENT',
}
