import type { SelectOption } from '../../../ui/Select';

const DHAKA_THANA_NAMES = [
  'Adabor',
  'Badda',
  'Bangshal',
  'Banani',
  'Bhashantek',
  'Bimanbandar / Airport',
  'Cantonment',
  'Chawkbazar',
  'Dakshinkhan',
  'Darus Salam',
  'Demra',
  'Dhanmondi',
  'Gandaria',
  'Gulshan',
  'Hatirjheel',
  'Hazaribagh',
  'Jatrabari',
  'Kadamtali',
  'Kafrul',
  'Kalabagan',
  'Kamrangirchar',
  'Khilgaon',
  'Khilkhet',
  'Kotwali',
  'Lalbagh',
  'Mirpur Model',
  'Mohammadpur',
  'Motijheel',
  'Mugda',
  'New Market',
  'Pallabi',
  'Paltan',
  'Ramna',
  'Rampura',
  'Rupnagar',
  'Sabujbagh',
  'Shah Ali',
  'Shahbag',
  'Shahjahanpur',
  'Sher-e-Bangla Nagar',
  'Shyampur',
  'Sutrapur',
  'Tejgaon',
  'Tejgaon Industrial Area',
  'Turag',
  'Uttara East',
  'Uttara West',
  'Uttarkhan',
  'Vatara',
  'Wari',
] as const;

export const DHAKA_THANA_OPTIONS: SelectOption[] = DHAKA_THANA_NAMES.map((name) => ({
  value: name,
  label: name,
}));
